name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master
      - hybrid

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        emacs_version:
          - 24.3
          - 24.4
          - 24.5
          - 25.1
          - 25.2
          - 25.3
          - 26.1
          - 26.2
          - 26.3
      # at most 20 concurrent jobs per free account
      # cf. https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#usage-limit
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2

    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - run: emacs --version
    - run: make
